### ISSUE TITLE
ページを閉じるとポーリングしなくなる

### ISSUE THREAD

**Issue by Ryo-7** [mokumoku-party/mobile-menu#5]
ローカルストレージは残るけど、オーダーidを入れていたstateProviderが揮発する？
受け取ってないのに完了になっちゃうし、受け取り完了ボタン押せなってしまう

**Comment by dicenull** [comment]
ローカルストレージに入れた情報以外は全部消えます。
残しておきたいstateProviderもローカルストレージに保存するとよさそう

**Comment by Ryo-7** [comment]
完成してデプロイしたので閉じます
